controller_list:
  - name: /floor/
    action_ns: joint_trajectory_action
    default: true
    type: FollowJointTrajectory
    joints:
      - floor_joint_a1
      - floor_joint_a2
      - floor_joint_a3
      - floor_joint_a4
      - floor_joint_a5
      - floor_joint_a6
  - name: /gantry
    action_ns: joint_trajectory_action
    default: true
    type: FollowJointTrajectory
    joints:
      - gantry_joint_e1
      - gantry_joint_e2
      - gantry_joint_e3
      - gantry_joint_a1
      - gantry_joint_a2
      - gantry_joint_a3
      - gantry_joint_a4
      - gantry_joint_a5
      - gantry_joint_a6
